### ISSUE TITLE
Invalid interface conversion

### ISSUE THREAD

**Issue by Inspirate789** [essentialkaos/aligo#156]
### Bug report

**System info:**

* aligo v2.1.3
* Debian GNU/Linux 12 (bookworm)
* Kernel 6.1.0-17-amd64
* Go 1.22.0 X:arenas (linux/amd64)

**Steps to reproduce:**

1. Create file `arena.go` with code
```go
//go:build goexperiment.arenas

package limited_arena

import (
	"arena"
	"github.com/Inspirate789/alloc/internal/limited_arena/constants"
	"reflect"
	"sync"
	"sync/atomic"
	"unsafe"
)

// Arena implements a size limit on the arena.Arena
type Arena struct {
	arena *arena.Arena
	free  uintptr
}

type gcMetadata struct {
	lastMarkID           uint64
	cyclicallyReferenced bool
	referenceCount       int // founded references (not all)
	Finalized            atomic.Bool
}

type ObjectMetadata struct {
	sync.RWMutex
	Address  unsafe.Pointer
	typeInfo reflect.Type
	arena    *Arena
	gcMetadata
}
```
2. execute command
```bash
aligo -s ObjectMetadata view .
```

**Expected behavior:**

I'm expecting to get the result of analyzing the structure `ObjectMetadata`.

**Actual behavior:**

I get a panic:
```go
––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
 ▾ github.com/Inspirate789/alloc/internal/limited_arena
––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

  // arena.go:27 | Size: 88
  type ObjectMetadata struct {
panic: interface conversion: types.Sizes is *types.gcSizes, not *types.StdSizes

goroutine 1 [running]:
github.com/essentialkaos/aligo/v2/inspect.GetMaxAlign(...)
        /home/inspirate789/go/pkg/mod/github.com/essentialkaos/aligo/v2@v2.1.3/inspect/inspect.go:81
github.com/essentialkaos/aligo/v2/cli.printCurrentFieldsInfo({0xc00036e940, 0x5, 0xc00003fbb0?})
        /home/inspirate789/go/pkg/mod/github.com/essentialkaos/aligo/v2@v2.1.3/cli/render.go:278 +0x2e6
github.com/essentialkaos/aligo/v2/cli.printStructInfo(0xc0002615e0, 0x0)
        /home/inspirate789/go/pkg/mod/github.com/essentialkaos/aligo/v2@v2.1.3/cli/render.go:257 +0xad
github.com/essentialkaos/aligo/v2/cli.PrintStruct(0xc00033f9e0, {0xc00027d4a0, 0xe}, 0x0)
        /home/inspirate789/go/pkg/mod/github.com/essentialkaos/aligo/v2@v2.1.3/cli/render.go:66 +0xf9
github.com/essentialkaos/aligo/v2/cli.process({0xc00007e440, 0x2, 0x1?})
        /home/inspirate789/go/pkg/mod/github.com/essentialkaos/aligo/v2@v2.1.3/cli/cli.go:203 +0x391
github.com/essentialkaos/aligo/v2/cli.Run({0x0, 0x0}, {0xb34f60, 0x15a, 0x15a})
        /home/inspirate789/go/pkg/mod/github.com/essentialkaos/aligo/v2@v2.1.3/cli/cli.go:118 +0x631
main.main()
        /home/inspirate789/go/pkg/mod/github.com/essentialkaos/aligo/v2@v2.1.3/aligo.go:27 +0x36
```

**Additional info:**
Your source file `inspect.go` where the panic is happening:
```go
package inspect

// ...

// GetMaxAlign returns MaxAlign
func GetMaxAlign() int64 {
	if Sizes == nil {
		return 8
	}

	return Sizes.(*types.StdSizes).MaxAlign
}
```
I think the problem might be caused by the fact that I'm using `//go:build goexperiment.arenas`, but it's not a good idea to convert interfaces so insecurely.

**Comment by andyone** [comment]
Hi! Could you please provide all information from `aligo -vv`?

**Comment by Inspirate789** [comment]
```
–– APPLICATION INFO ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

  Name:     aligo
  Version:  2.1.3
  Go:       1.22.0 X:arenas (linux/amd64)
  Bin SHA:  50006f8

–– OS INFO –––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

  Name:          Debian GNU/Linux
  Pretty Name:   Debian GNU/Linux 12 (bookworm)
  Version:       12 (bookworm)
  ID:            debian
  ID Like:       —
  Version ID:    12
  Version Code:  bookworm
  Platform ID:   —
  CPE:           —
  Arch:          x86_64
  Kernel:        6.1.0-17-amd64

  Container:     Yes (Docker)

–– APPLICATIONS ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

  golang:  1.22.0

–– DEPENDENCIES ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

 12.118.0  github.com/essentialkaos/ek
    1.0.0  github.com/kisielk/gotool
   0.20.0  golang.org/x/tools

––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

```

**Comment by andyone** [comment]
> but it's not a good idea to convert interfaces so insecurely

It was quite okay until Go 1.22. 

I got this problem earlier and made a fix in 9f1a7ef01d996a577bfae5e970692ca5a15c1c1c. This fix will be part of the upcoming [2.2.0](https://github.com/essentialkaos/aligo/pull/155) release. Anyway, thanks for reporting this.

**Comment by Inspirate789** [comment]
Спасибо, Антон!
Буду ждать релиза

**Comment by andyone** [comment]
Version 2.2.0 [has been released](https://kaos.sh/aligo/2.2.0).
